### ISSUE TITLE
unable to run knex table migrations

### ISSUE THREAD

**Issue by agyin3** [Lambda-School-Labs/lets-get-pizza-be#33]
When creating a postgres database on my local machine for development and testing there is an issue when running the migration files. When I run `knex migrate:latest` I receive the following error message 
```
migration file "20191030123028_event.js" failed
migration failed with error: alter table "events" add constraint "events_user_id_foreign" foreign key ("user_id") references "users" ("id") - relation "users" does not exist
error: relation "users" does not exist
    at Connection.parseE (/Users/buddyagyin/Desktop/labs-project/lets-get-pizza-be/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/Users/buddyagyin/Desktop/labs-project/lets-get-pizza-be/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/Users/buddyagyin/Desktop/labs-project/lets-get-pizza-be/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:219:5)
    at addChunk (_stream_readable.js:332:12)
    at readableAddChunk (_stream_readable.js:307:11)
    at Socket.Readable.push (_stream_readable.js:241:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:185:23)
```

It seems like the order the tables/migration files were created is causing this issue

**Comment by Katrina-Dierking** [comment]
Tested on my end. Works great.
